name: Build and Analyze Qt Project

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install Qt (via Chocolatey)
      - name: Install Qt
        run: choco install qt6-default --confirm

      # Install SonarCloud tools
      - name: Install SonarCloud tools
        uses: sonarsource/sonarcloud-github-c-cpp@v3

      # Build the project using qmake
      - name: Build project with qmake
        run: |
          qmake src/cproject.pro
          make

      # Run SonarCloud analysis
      - name: Run SonarCloud analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner
